fix: upgrade zip to v4
zip v2.6 got yanked

```
cargo add calamine

error: failed to select a version for the requirement `zip = "^2.6"`
candidate versions found which didn't match: 4.0.0, 3.0.0, 2.4.2, ...
```

calamine is not effected by changes from v2.6 to v4